version: "3"
services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - .:/node_modules
    command: "nodemon start"
    ports:
      - 8238:8238